APP: Blurrr_IOS
Assert_Msg: All
ENV: PROD
Global_Exported: true
Global_Var:
  Global_Mobile_User_Token: T0dEWkxvUkt4ampDYnc4dFAvQWlnRHMzcklsVnVzdW5IQ21SV1Y0TGwxazc5OVJpTjcveC9YZnNnWHYvaU43eTdFQjVMMnhkZm1RVmh0V1l2MnhrLzg4TUk4V0ZYNFdXcVJ5b1FtM21vNElNdXBteXZJVkFQdzRTU3JUOGdpMFRMblVlNjNoUnBYY1FhQTVnTEQzMmF2NG9NZXZMZVVtWQ==
  Global_Mobile_User_Token_2: ZmoyaXBYd3Q4Q3l1VEtDZzhiVXdVMXUxQ0pvU2dUcUkvQWQzS1hTQmxjb2oycVRlZWZOWnF2MUNkdVJ3Ty9OdzBtZjZHWXRRTlJiOU9WMmlZc0tTRHMzUjRoVjN2OXB1SG1HaW12MEFOMFZDVFk4VjBHOHcrZXdwNlIrai9iM2g5R0RLWk02UXBxOEdkWExIMnc1UUpTeWp1L242NUlJMA==
  Global_User_Id: 03c81d5d847ea22e5a1a6770
  Global_User_Id_2: 0be97a5a4b56eae3199664c8
LOG_Level: info
MOD: "videobeats_servertime,videobeats_juice\u4F59\u989D,videobeats_juiceconfig,videobeats_juice_\u8D60\
  \u9001\u914D\u7F6E,videobeats_juice_\u8D60\u9001\u8BB0\u5F55,videobeats_juice_\u8D2D\
  \u4E70\u8BB0\u5F55,videobeats_\u679C\u6C41\u8D60\u9001,videobeats_uservip\u4FE1\u606F\
  ,videobeats_\u7528\u6237\u5728\u7EBF\u72B6\u6001,videobeats_\u7ED1\u5B9A\u8BBE\u5907\
  \u4F1A\u5458\u5230\u7528\u6237,videobeats_\u83B7\u53D6\u4E91\u7A7A\u95F4\u5927\u5C0F\
  ,videobeats_\u67E5\u8BE2\u4E91\u7A7A\u95F4\u5217\u8868,videobeats_\u8BBE\u7F6E\u5DE5\
  \u7A0B\u6536\u76CA\u6570\u636E\u4E3A\u5DF2\u8BFB,videobeats_\u4E8C\u7EF4\u7801\u83B7\
  \u53D6\u5DE5\u7A0B\u4FE1\u606F,videobeats_\u52A8\u6001\u7D20\u6750\u5217\u8868,videobeats_\u97F3\
  \u6548\u5E93\u5217\u8868,videobeats_\u7279\u6548\u5206\u7C7B,videobeats_\u4E2A\u4EBA\
  \u4E2D\u5FC3\u8FD0\u8425banner,videobeats_\u7279\u6548\u5217\u8868,Global"
PRIO: '4'
TIMEOUT: '10'
TestList:
- /Users/xiannvxiao/PycharmProjects/APITesting/TestCase/Blurrr_IOS/videobeats_servertime/servertime.py
- "/Users/xiannvxiao/PycharmProjects/APITesting/TestCase/Blurrr_IOS/videobeats_juice\u4F59\
  \u989D/juicecount.py"
- /Users/xiannvxiao/PycharmProjects/APITesting/TestCase/Blurrr_IOS/videobeats_juiceconfig/juiceconfig.py
- "/Users/xiannvxiao/PycharmProjects/APITesting/TestCase/Blurrr_IOS/videobeats_juice_\u8D60\
  \u9001\u914D\u7F6E/juicegiftconfig.py"
- "/Users/xiannvxiao/PycharmProjects/APITesting/TestCase/Blurrr_IOS/videobeats_juice_\u8D60\
  \u9001\u8BB0\u5F55/juicegiftlog.py"
- "/Users/xiannvxiao/PycharmProjects/APITesting/TestCase/Blurrr_IOS/videobeats_juice_\u8D2D\
  \u4E70\u8BB0\u5F55/juice.py"
- "/Users/xiannvxiao/PycharmProjects/APITesting/TestCase/Blurrr_IOS/videobeats_\u679C\
  \u6C41\u8D60\u9001/monthVIP.py"
- "/Users/xiannvxiao/PycharmProjects/APITesting/TestCase/Blurrr_IOS/videobeats_\u679C\
  \u6C41\u8D60\u9001/foreverVIP.py"
- "/Users/xiannvxiao/PycharmProjects/APITesting/TestCase/Blurrr_IOS/videobeats_\u679C\
  \u6C41\u8D60\u9001/login.py"
- "/Users/xiannvxiao/PycharmProjects/APITesting/TestCase/Blurrr_IOS/videobeats_\u679C\
  \u6C41\u8D60\u9001/yearVIP.py"
- "/Users/xiannvxiao/PycharmProjects/APITesting/TestCase/Blurrr_IOS/videobeats_uservip\u4FE1\
  \u606F/novip.py"
- "/Users/xiannvxiao/PycharmProjects/APITesting/TestCase/Blurrr_IOS/videobeats_uservip\u4FE1\
  \u606F/vipuser.py"
- "/Users/xiannvxiao/PycharmProjects/APITesting/TestCase/Blurrr_IOS/videobeats_\u7528\
  \u6237\u5728\u7EBF\u72B6\u6001/user.py"
- "/Users/xiannvxiao/PycharmProjects/APITesting/TestCase/Blurrr_IOS/videobeats_\u7ED1\
  \u5B9A\u8BBE\u5907\u4F1A\u5458\u5230\u7528\u6237/bindvip.py"
- "/Users/xiannvxiao/PycharmProjects/APITesting/TestCase/Blurrr_IOS/videobeats_\u83B7\
  \u53D6\u4E91\u7A7A\u95F4\u5927\u5C0F/project.py"
- "/Users/xiannvxiao/PycharmProjects/APITesting/TestCase/Blurrr_IOS/videobeats_\u67E5\
  \u8BE2\u4E91\u7A7A\u95F4\u5217\u8868/project(\u67E5\u8BE2\u81EA\u52A8\u5316\u6D4B\
  \u8BD5\u4E91\u7AEF\u9879\u76EE).py"
- "/Users/xiannvxiao/PycharmProjects/APITesting/TestCase/Blurrr_IOS/videobeats_\u67E5\
  \u8BE2\u4E91\u7A7A\u95F4\u5217\u8868/project.py"
- "/Users/xiannvxiao/PycharmProjects/APITesting/TestCase/Blurrr_IOS/videobeats_\u8BBE\
  \u7F6E\u5DE5\u7A0B\u6536\u76CA\u6570\u636E\u4E3A\u5DF2\u8BFB/vipuser.py"
- "/Users/xiannvxiao/PycharmProjects/APITesting/TestCase/Blurrr_IOS/videobeats_\u4E8C\
  \u7EF4\u7801\u83B7\u53D6\u5DE5\u7A0B\u4FE1\u606F/vipuser.py"
- "/Users/xiannvxiao/PycharmProjects/APITesting/TestCase/Blurrr_IOS/videobeats_\u52A8\
  \u6001\u7D20\u6750\u5217\u8868/\u52A8\u6001\u7D20\u6750\u5217\u8868.py"
- "/Users/xiannvxiao/PycharmProjects/APITesting/TestCase/Blurrr_IOS/videobeats_\u97F3\
  \u6548\u5E93\u5217\u8868/juice.py"
- "/Users/xiannvxiao/PycharmProjects/APITesting/TestCase/Blurrr_IOS/videobeats_\u7279\
  \u6548\u5206\u7C7B/\u7279\u6548\u5206\u7C7B.py"
- "/Users/xiannvxiao/PycharmProjects/APITesting/TestCase/Blurrr_IOS/videobeats_\u4E2A\
  \u4EBA\u4E2D\u5FC3\u8FD0\u8425banner/\u7279\u6548\u5206\u7C7B.py"
- "/Users/xiannvxiao/PycharmProjects/APITesting/TestCase/Blurrr_IOS/videobeats_\u7279\
  \u6548\u5217\u8868/\u7279\u6548\u5217\u8868.py"
